language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PINS="mirage-flow.2.0.0:git+https://github.com/hannesm/mirage-flow.git#easy mirage-flow-combinators.2.0.0:git+https://github.com/hannesm/mirage-flow.git#easy mirage-clock.3.0.0:git+https://github.com/hannesm/mirage-clock.git#easy"
   - PACKAGE="mirage-channel"
 matrix:
   - DISTRO=alpine OCAML_VERSION=4.06
   - DISTRO=alpine OCAML_VERSION=4.07
   - DISTRO=alpine OCAML_VERSION=4.08
   - DISTRO=alpine OCAML_VERSION=4.09
